# -*- coding: utf-8 -*-
"""Stock Market project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8qj4eeOUjD_WfvhWbkLmo3Y0YX1JuMS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
data = pd.read_csv("/content/drive/MyDrive/Stock_data.csv")
data['Date'] = pd.to_datetime(data['Date'])
data = data.sort_values('Date')
data.set_index('Date', inplace=True)
if 'Volume' not in data.columns:
    data['Volume'] = 0
data['MA20'] = data['Close'].rolling(window=20).mean()
def calculate_rsi(series, period=14):
    delta = series.diff()
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    avg_gain = gain.rolling(period).mean()
    avg_loss = loss.rolling(period).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi
data['RSI'] = calculate_rsi(data['Close'])
data.dropna(inplace=True)
features = ['Open', 'High', 'Low', 'Close', 'Volume', 'MA20', 'RSI']
data = data[features]
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
sequence_length = 60
X = []
y = []
for i in range(sequence_length, len(scaled_data)):
    X.append(scaled_data[i-sequence_length:i])
    y.append(scaled_data[i][3])
X = np.array(X)
y = np.array(y)
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]
model = Sequential()
model.add(LSTM(64, return_sequences=True, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
model.add(LSTM(64))
model.add(Dropout(0.2))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X_train, y_train, epochs=20, batch_size=32)
predictions = model.predict(X_test)
close_scaler = MinMaxScaler()
close_scaler.fit(data[['Close']])
actual_prices = close_scaler.inverse_transform(y_test.reshape(-1,1))
predicted_prices = close_scaler.inverse_transform(predictions)
plt.figure(figsize=(12,6))
plt.plot(actual_prices, label='Actual Price')
plt.plot(predicted_prices, label='Predicted Price')
plt.title("Actual vs Predicted Stock Price")
plt.legend()
plt.show()
actual_series = pd.Series(actual_prices.flatten())
predicted_series = pd.Series(predicted_prices.flatten())
actual_direction = np.where(actual_series.diff() > 0, 1, 0)
predicted_direction = np.where(predicted_series.diff() > 0, 1, 0)
actual_direction = actual_direction[1:]
predicted_direction = predicted_direction[1:]
trend_accuracy = np.mean(actual_direction == predicted_direction) * 100
print("Overall Trend Accuracy: {:.2f}%".format(trend_accuracy))
window = 10
rolling_accuracy = []
for i in range(window, len(actual_direction)):
    actual_window = actual_direction[i-window:i]
    pred_window = predicted_direction[i-window:i]
    acc = np.mean(actual_window == pred_window) * 100
    rolling_accuracy.append(acc)
rolling_accuracy = pd.Series(rolling_accuracy)
plt.figure(figsize=(12,6))
plt.plot(rolling_accuracy)
plt.axhline(y=50, linestyle='--')
plt.title("Rolling 10-Day Trend Accuracy")
plt.xlabel("Time")
plt.ylabel("Accuracy (%)")
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
price = data['Close']
market_returns = price.pct_change().fillna(0)
if 'predicted_returns' not in globals():
    np.random.seed(42)
    predicted_returns = pd.Series(
        np.random.normal(0, 0.01, len(price)),
        index=price.index
    )
predicted_returns = predicted_returns.reindex(price.index).fillna(0)
signals = np.where(predicted_returns > 0, 1, -1)
signals = pd.Series(signals, index=price.index)
signals = signals.shift(1).fillna(0)
strategy_returns = signals * market_returns
buy_hold_returns = market_returns
strategy_cum = (1 + strategy_returns).cumprod()
buy_hold_cum = (1 + buy_hold_returns).cumprod()
initial_capital = 10000
strategy_portfolio = initial_capital * strategy_cum
buy_hold_portfolio = initial_capital * buy_hold_cum
print("Final Strategy Capital: ₹", round(strategy_portfolio.iloc[-1], 2))
print("Final Buy & Hold Capital: ₹", round(buy_hold_portfolio.iloc[-1], 2))
annual_return = strategy_returns.mean() * 252
annual_volatility = strategy_returns.std() * np.sqrt(252)
sharpe_ratio = annual_return / annual_volatility
rolling_max = strategy_portfolio.cummax()
drawdown = (strategy_portfolio - rolling_max) / rolling_max
max_drawdown = drawdown.min()
print("\nPerformance Metrics")
print("---------------------")
print(f"Annual Return: {annual_return*100:.2f}%")
print(f"Annual Volatility: {annual_volatility*100:.2f}%")
print(f"Sharpe Ratio: {sharpe_ratio:.2f}")
print(f"Maximum Drawdown: {max_drawdown*100:.2f}%")
plt.figure(figsize=(12,6))
plt.plot(market_returns, label='Actual Returns')
plt.plot(predicted_returns, label='Predicted Returns')
plt.title("Actual vs Predicted Returns")
plt.legend()
plt.grid()
plt.show()
plt.figure(figsize=(12,6))
plt.plot(price, label='Price')
buy_signals = price[signals == 1]
sell_signals = price[signals == -1]
plt.scatter(buy_signals.index, buy_signals, marker='^', color='green', label='Buy')
plt.scatter(sell_signals.index, sell_signals, marker='v', color='red', label='Sell')
plt.title("Price with Buy & Sell Signals")
plt.legend()
plt.grid()
plt.show()
plt.figure(figsize=(12,6))
plt.plot(strategy_cum, label='Strategy')
plt.plot(buy_hold_cum, label='Buy & Hold')
plt.title("Cumulative Returns")
plt.legend()
plt.grid()
plt.show()
plt.figure(figsize=(12,6))
plt.plot(strategy_portfolio, label='Strategy Portfolio')
plt.plot(buy_hold_portfolio, label='Buy & Hold Portfolio')
plt.title("Capital Growth (₹10,000 Initial Investment)")
plt.ylabel("Portfolio Value (₹)")
plt.legend()
plt.grid()
plt.show()
trade_changes = signals.diff()
trade_entries = price[trade_changes != 0]
trade_profits = []
for i in range(len(trade_entries)-1):
    entry_price = trade_entries.iloc[i]
    exit_price = trade_entries.iloc[i+1]
    direction = signals.loc[trade_entries.index[i]]
    profit = (exit_price - entry_price) / entry_price * direction
    trade_profits.append(profit)
plt.figure(figsize=(12,6))
plt.bar(range(len(trade_profits)), trade_profits)
plt.title("Profit per Trade")
plt.xlabel("Trade Number")
plt.ylabel("Return per Trade")
plt.grid()
plt.show()